<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { useRouter } from 'vue-router'
import AppShell from '@/components/AppShell.vue'
import PageState from '@/components/PageState.vue'
import ActivityList from '@/components/ActivityList.vue'
import { useAuthStore } from '@/stores/auth'
import { createSubscription, deleteSubscription, getFavorites, getNotifications, getSubscriptions, markAllNotificationsRead, markNotificationRead, updateProfile, type Notification, type Subscription } from '@/api/profile'
import type { Activity } from '@/api/activities'

const auth=useAuthStore(); const router=useRouter(); const active=ref('overview'); const loading=ref(false); const error=ref(''); const favorites=ref<Activity[]>([]); const subscriptions=ref<Subscription[]>([]); const notifications=ref<Notification[]>([]); const keyword=ref(''); const displayName=ref(auth.user?.display_name || auth.user?.username || ''); const email=ref(auth.user?.email || '')
function logout(){ auth.logout(); router.replace('/') }
const unreadCount=computed(()=>notifications.value.filter(x=>!x.read).length)
async function load(){loading.value=true;error.value='';try{const [favoriteResult,subscriptionResult,notificationResult]=await Promise.allSettled([getFavorites(),getSubscriptions(),getNotifications()]);if(favoriteResult.status==='fulfilled')favorites.value=favoriteResult.value.data.items;if(subscriptionResult.status==='fulfilled')subscriptions.value=subscriptionResult.value.data.items;if(notificationResult.status==='fulfilled')notifications.value=notificationResult.value.data.items;const unavailable=[favoriteResult,subscriptionResult,notificationResult].filter(x=>x.status==='rejected').length;if(unavailable===3)error.value='个人数据加载失败';else if(unavailable)ElMessage.warning('部分个人数据暂不可用')}finally{loading.value=false}}
async function save(){try{const {data}=await updateProfile({display_name:displayName.value,email:email.value});const user=data&&typeof data==='object'&&'user' in data?data.user:data;if(!user)throw new Error('资料保存失败');auth.user=user;localStorage.setItem('user',JSON.stringify(user));ElMessage.success('资料已保存')}catch{}}
async function addSubscription(){if(!keyword.value.trim())return;try{subscriptions.value.push((await createSubscription(keyword.value.trim())).data);keyword.value='';ElMessage.success('订阅已添加')}catch{}}
async function removeSubscription(id:number){try{await deleteSubscription(id);subscriptions.value=subscriptions.value.filter(x=>x.id!==id);ElMessage.success('订阅已取消')}catch{}}
async function read(id:number){try{await markNotificationRead(id);const current=notifications.value.find(x=>x.id===id);if(current)current.read=true}catch{}}
async function readAll(){try{await markAllNotificationsRead();notifications.value.forEach(x=>x.read=true);ElMessage.success('已全部标记为已读')}catch{}}
onMounted(load)
</script>
<template><AppShell title="个人中心"><PageState :loading="loading" :error="error" @retry="load"><div class="profile-grid"><aside class="surface-card profile-card"><el-avatar :size="72">{{ auth.user?.username.slice(0,1) }}</el-avatar><h2>{{ auth.user?.display_name || auth.user?.username }}</h2><p>{{ auth.user?.role }}</p><el-button @click="logout">退出登录</el-button></aside><section class="surface-card profile-content"><el-tabs v-model="active"><el-tab-pane label="概览" name="overview"><el-form label-position="top" class="profile-form"><el-form-item label="显示名称"><el-input v-model="displayName"/></el-form-item><el-form-item label="邮箱"><el-input v-model="email"/></el-form-item><el-button type="primary" @click="save">保存资料</el-button></el-form></el-tab-pane><el-tab-pane label="我的收藏" name="favorites"><el-empty v-if="!favorites.length" description="还没有收藏活动"/><ActivityList v-else :activities="favorites"/></el-tab-pane><el-tab-pane label="订阅" name="subscriptions"><div class="subscribe-box"><el-input v-model="keyword" placeholder="输入关键词订阅" @keyup.enter="addSubscription"/><el-button type="primary" @click="addSubscription">添加</el-button></div><el-empty v-if="!subscriptions.length" description="暂无订阅"/><el-tag v-for="item in subscriptions" v-else :key="item.id" closable class="subscription" @close="removeSubscription(item.id)">{{item.keyword}}</el-tag></el-tab-pane><el-tab-pane :label="`通知${unreadCount ? ` (${unreadCount})` : ''}`" name="notifications"><div class="notify-head"><span>未读 {{ unreadCount }} 条</span><el-button text type="primary" @click="readAll">全部已读</el-button></div><el-empty v-if="!notifications.length" description="暂无通知"/><button v-for="item in notifications" v-else :key="item.id" type="button" class="notification" :class="{unread:!item.read}" :aria-label="`标记通知为已读：${item.title}`" @click="read(item.id)"><strong>{{item.title}}</strong><p>{{item.body}}</p><time>{{new Date(item.created_at).toLocaleString('zh-CN')}}</time></button></el-tab-pane></el-tabs></section></div></PageState></AppShell></template>
<style scoped>.profile-grid{display:grid;grid-template-columns:240px minmax(0,1fr);gap:20px}.profile-card{padding:26px;text-align:center;height:max-content}.profile-card h2{color:var(--brand-dark);margin:12px 0 4px}.profile-card p{color:var(--text-muted);margin-bottom:18px}.profile-content{padding:22px}.profile-form{max-width:520px}.subscribe-box{display:flex;gap:10px;margin-bottom:16px;max-width:460px}.subscription{margin:0 8px 8px 0}.notify-head{display:flex;justify-content:space-between;margin-bottom:10px}.notification{display:block;width:100%;border:0;border-top:1px solid var(--line);padding:14px;background:transparent;text-align:left;cursor:pointer}.notification.unread{border-left:3px solid var(--brand-accent);background:var(--brand-soft)}.notification:focus-visible{outline:2px solid var(--brand-accent);outline-offset:2px}.notification p,.notification time{margin:5px 0 0;color:var(--text-muted);font-size:13px}@media(max-width:700px){.profile-grid{grid-template-columns:1fr}.profile-card{display:flex;gap:12px;align-items:center;text-align:left}.profile-card h2{margin:0}.subscribe-box{max-width:none}}</style>
